spring.application.name=consumer_rework
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.message.topic=topic-name
spring.kafka.consumer.message.group-id=topic-name
server.port=8081
